sudo: false
language: node_js
node_js:
  - "4.3"
env:
  - DEPLOYMENT_ENV=development
script: npm test
after_success: node-lambda deploy -a $AWS_DEPLOY_USER_ACCESS_KEY -s $AWS_DEPLOY_USER_SECRET_KEY --role arn:aws:iam::810905322061:role/lambda_kinesis_role -e $DEPLOYMENT_ENV -d "Processes motion detected events from Kinesis stream (Travis build: $TRAVIS_BUILD_NUMBER, Commit id: $TRAVIS_COMMIT)" --configFile deploy.env
